services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: telegram
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: telegrambot
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}
      TELEGRAM_BOT_TOKEN:    ${TELEGRAM_BOT_TOKEN}

volumes:
  db_data:
