version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: telegrambot
      MYSQL_USER: telegrambot
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  app:
    build: .
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}
    ports:
      - "8080:8080"
    depends_on:
      - db