telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:7965265400:AAHUgw--kRWmzawqEUyYK8jxGLYHXEuZCv8}
    username: ${TELEGRAM_BOT_USERNAME:MyTestBot}


spring:
  jpa:
    properties:
      hibernate.type.json_format_mapper: jackson

