telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}

spring:
  datasource:
    url: jdbc:h2:mem:telegrambot
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
logging:
  level:
    com.qqunty.telegrambot: INFO
