telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}

spring:
  jpa:
    hibernate:
      ddl-auto: update        # чтобы таблицы создавались сами
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:telegrambot
    driverClassName: org.h2.Driver
    username: sa
    password:
logging:
  level:
    com.qqunty.telegrambot: INFO
